name: task2
run-name: task2
on: [push, pull_request]
jobs:
  task2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          working-directory: desktop-app
          node-version: lts/*
          cache: "npm"

      - run: |
          cd desktop-app
          npm install

      - run: |
          cd desktop-app
          npm test
