name: task2
run-name: task2
on: [push, pull_request]
jobs:
  task2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: cd desktop-app
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: subdir/package-lock.json
      - run: npm ci
      - run: npm test
