name: task2
run-name: task2
on: [push, pull_request]
jobs:
  task2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./desktop-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: cd desktop-app
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm install
      - run: npm test
