name: task1
run-name: task1
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo $GITHUB_REF

      - run: ls -lahR
